version: "3.9"

services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes: 
      - ./volumes/postgresdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
    ports:
      - "8080:${PGADMIN_PORT}"
    volumes:
      - ./volumes/pgadmindata:/var/lib/pgadmin
    depends_on:
      - postgres

  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASS}
    ports: 
      - ${REDIS_PORT}:${REDIS_PORT}
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      
  redisinsight:
    image: redislabs/redisinsight
    container_name: redisinsight
    ports:
      - ${REDIS_INSIGHT_PORT}:${REDIS_INSIGHT_PORT}
    volumes:
      - ./volumes/redisinsight:/var/lib/redisinsight/db

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    volumes:
      - ./volumes/esdata:/var/lib/esdata/data
    environment:
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASS}
      # - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=true
    logging:
      driver: none
    ports:
      - ${ELASTIC_PORT}:${ELASTIC_PORT}

  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.0
    container_name: kibana
    environment:
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASS}
      - ELASTICSEARCH_URL=${ELASTIC_URL}
    ports:
      - ${KIBANA_PORT}:${KIBANA_PORT}
    depends_on:
      - elasticsearch

volumes:
  postgresdata:
  pgadmindata:
  redisinsight: